version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      security-fixes:
        applies-to: security-updates
        update-types: ["patch", "minor", "major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "actions"]
    commit-message:
      prefix: "deps"
